project:
  type: website
  output-dir: docs

website:
  title: "Two Points Make a Line"
  site-url: https://twopoints.blog
  description: "A blog about visualizing data"
  favicon: /images/logo-icon.png
  repo-url: https://github.com/ksreyes/twopoints
  image: /images/logo-icon.png
  google-analytics: "G-EJMC44PZ56"
  cookie-consent: true
  search: true
  margin-header: rbloggers.html
  navbar:
    logo: /images/logo-icon-invert.png
    left: 
      - text: "Telling stories through visualized data by Kenneth S. Reyes"
    right:
      - href: subscribe.qmd
        text: "Subscribe"
      - href: about.qmd
        text: "About"
      - icon: github
        href: https://github.com/ksreyes/twopoints
      - icon: rss
        href: index.xml
        
format:
  html:
    theme: 
      - default
      - custom.scss

editor: source

resources:
  - CNAME
